version: 2
jobs:
  build:
    docker:
    - image: endreymarca/jiraf-testing
    working_directory: /jiraf
    steps:
    - checkout:
        path: /git_jiraf
    - run:
        name: Copy the source code from git to the testing folder
        command: cp -r /git_jiraf/* /jiraf/
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Lint and test
        command: npm run lint && npm test
