version: 2
jobs:
  build:
    docker:
    - image: endreymarca/jiraf-testing
    working_directory: /jiraf
    steps:
    - checkout:
        path: /git_jiraf
    - run:
        name: Copy the source code from git to the testing folder
        command: cp -r /git_jiraf/* /jiraf/
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Start mock JIRA server in the background
        command: node test/mocks/jira.js
        background: true
    - run:
        name: Start mock GitHub server in the background
        command: node test/mocks/github.js
        background: true
    - run:
        name: Wait until the mock JIRA service is up
        command: wget -O/dev/null --quiet --retry-connrefused --wait=1 --tries=10 --timeout=15 http://127.0.0.1/healthcheck
    - run:
        name: Wait until the mock GitHub service is up
        command: wget -O/dev/null --quiet --retry-connrefused --wait=1 --tries=10 --timeout=15 http://127.0.0.2/healthcheck
    - run:
        name: curl mock JIRA service by IP
        command: curl 127.0.0.1/debug
    - run:
        name: curl mock GitHub service by IP
        command: curl 127.0.0.2/debug
    - run:
        name: Lint and test
        command: npm run lint && npm run test:docker
