version: 2
jobs:
  build:
    docker:
    - image: endreymarca/jiraf-testing
    working_directory: /jiraf
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run: npm run lint && npm run functional-test
