version: 2
jobs:
  build:
    docker:
    - image: endreymarca/jiraf-testing
    working_directory: /jiraf
    steps:
    - add_ssh_keys:
        fingerprints:
        - "2e:b5:40:44:d9:21:b4:c5:8f:d1:69:19:4e:14:2d:bb"
    - checkout:
        path: /git_jiraf
    - run:
        name: Copy the source code from git to the testing folder
        command: cp -r /git_jiraf/. /jiraf/ && rm -rf /jiraf/.git/
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package-lock.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm ci
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package-lock.json" }}
    - run:
        name: Start mock JIRA server in the background
        command: node test/mocks/jira/jira.js
        background: true
    - run:
        name: Start mock GitHub server in the background
        command: node test/mocks/github/github.js
        background: true
    - run:
        name: Wait until the mock JIRA service is up
        command: wget -O/dev/null --quiet --retry-connrefused --wait=1 --tries=10 --timeout=15 http://127.0.0.1/healthcheck
    - run:
        name: Wait until the mock GitHub service is up
        command: wget -O/dev/null --quiet --retry-connrefused --wait=1 --tries=10 --timeout=15 http://127.0.0.2/healthcheck
    - run:
        name: curl mock JIRA service by IP
        command: curl 127.0.0.1/debug
    - run:
        name: curl mock GitHub service by IP
        command: curl 127.0.0.2/debug
    - run:
        name: Static code checks
        command: npm run lint
    - run:
          name: Functional tests
          command: npm run test
    - run:
        name: Setup environment variables
        command: |
            echo 'export GITHUB_USERNAME="$GITHUB_USERNAME"' >> $BASH_ENV
            echo 'export GITHUB_API_TOKEN="$GITHUB_API_TOKEN"' >> $BASH_ENV
    - run:
        name: Integration tests
        command: npm run integration
